title: Amy Dryden 
logo: https://github.com/acedryden/acedryden.github.io/blob/main/assets/testpic.jpg
#description text below image 
show_downloads: false
#google_analytics: [Your Google Analytics tracking ID]
theme: jekyll-theme-minimal
